- moz_telemetry/modules/moz_telemetry/extract_dimensions.lua
It's easier to investigate / debug if you can look at the original
message that caused an error.
> Include the full raw message in the error message

- elasticsearch/CMakeLists.txt
- elasticsearch/sandboxes/heka/output/elasticsearch_bulk_api.lua
When the sandbox is being shutdown and the `flush_on_shutdown` option is set, the batch file need to be emptied or its content will be sent twice to elastic search.
> Ensure the batch file is emptied on shutdown

- moz_telemetry/io_modules/decoders/moz_telemetry/ping.lua
Per https://github.com/mozilla-services/data-pipeline/blob/master/heka/sandbox/decoders/extract_telemetry_dimensions.lua#L206
> Extract payload objects from saved-session pings

- moz_telemetry/io_modules/decoders/moz_telemetry/ping.lua
This will enable storing the pingsender version that
comes from the headers of the pings sent with it.
> Add the pingSenderVersion field to the decoder

- elasticsearch/CMakeLists.txt
- elasticsearch/sandboxes/heka/output/elasticsearch_bulk_api.lua
Explicitly send Content-Type header during POST in ES bulk api
* Fixes this warning returned by ES if this header is missing : "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header."
> Content type header

- jose/tests/test.lua
With debian jessie-backports libcjose-dev:0.4.1-3~bpo8+1, jose tests fail due to different line numbers referenced in the error messages. This PR changes those tests to be pattern matches with the line number matched to %d+. Other tests were left as string comparisons to avoid escaping ?'s and ()'s.
> Use patterns to make jose test pass

- syslog/modules/lpeg/linux/kernel.lua
- syslog/tests/linux/kernel.lua
Extends original kernel grammar which handled netfilter logs to also
handle parsing segfault messages.
> add lpeg grammar for segfault logging from linux kernel

- geoip/CMakeLists.txt
- geoip/CMakeLists.txt.geoip
- geoip/io_modules/geoip/geo_append.lua
- moz_security/sandboxes/heka/analysis/moz_security_sshd_login_monitor.lua
- moz_security/tests/hindsight/run/input/generate_sshd.cfg
- moz_security/tests/hindsight/run/input/generate_sshd.lua
- moz_security/tests/hindsight/run/output/sshd_login_verification.lua
Intended to be used with other io_modules such as decoders; extends
existing message with GeoIP information for any fields that match an
IPv4 address expression. The GeoIP information is added with a postfix
along side the original field value.
Resolves #190
> io_module to extend heka message with GeoIP information

- maxminddb/CMakeLists.txt.maxminddb
- maxminddb/io_modules/maxminddb/heka.lua
This module was ported from geoip and the close() call not removed
causing the reopen and all future lookups to fail.
> Remove the unsupported call to close() for maxminddb

- CMakeLists.txt
- irc/CMakeLists.txt
- irc/index.md
- irc/irc.c
- moz_security/CMakeLists.txt
- moz_security/index.md
Adds a new IO module that can be used to implement a persistent connection to an IRC server from an output sandbox. The calling Lua sandbox can make use of `new` that will create a background thread, and subsequent calls to `write_chan` on the returned object will queue strings for output in a given channel.
```
i = require "irc"
c = i.new("nick", "server.host", 6697, "#test")
c:write_chan("test message")
```
> prototype iomodule for irc integration in output plugins

- elasticsearch/CMakeLists.txt
- elasticsearch/sandboxes/heka/output/elasticsearch_bulk_api.lua
When index is read only, all messages will be dropped instead of retrying until
an admin fix the cluster
This is an RFC (not even tested), we might want to only match some status
I'll finish next week, but if you already have comments please share :)
>  elasticsearch: don't drop messages when all status are 403

- gcp/CMakeLists.txt
- gcp/pubsub.cpp
- gcp/pubsub.md
The initial version simply called 'create' and ignored an already exists error.
However, that requires more permissions, so now a 'get' is attempted and if
that fails with a not found error then create is tried.
An error is now generated if the subscription topic does not match the specified
topic, this is a safety check to prevent confusion in the case where the subscription
name is already in use on another topic.
> Issues 332, 333 - Call Get() before Create()

- moz_security/sandboxes/heka/analysis/moz_security_cloudtrail.lua
- moz_security/tests/integration/analysis_cloudtrail/run/analysis/cloudtrail.cfg
This is particularly useful for when matching against multiple aws account ids. As well, in moz_security_cloudtrail we are currently using `string.match` which does not have an `or` operator.
As well, this PR adds an example of a `not` operation within `string.match`.
> Support multiple matchers per field for cloudtrail

- moz_security/sandboxes/heka/analysis/moz_security_cloudtrail.lua
- moz_security/tests/integration/analysis_cloudtrail/run/analysis/cloudtrail.cfg
Switch to using lpeg.re within cloudtrail analysis sandbox so that field
matchers can be more expressive. Also allows for the removal of logic
supporting multiple matchers against an event field.
r? @ameihm0912 @trink
> Use lpeg.re for matching in cloudtrail sandbox

- moz_security/io_modules/taskcluster.lua
- moz_security/test_sandbox.c
- moz_security/tests/taskcluster.lua
Adds the `taskcluster#add_username` func that can be used with another
decoder to extract the ldap username from a taskcluster clientid. This
makes plugging into other analysis sandboxes much simpler.
Blocked by https://github.com/mozilla-services/lua_sandbox_extensions/issues/381
r? @ameihm0912
> Extract usernames from Taskcluster audit logs

- socket/CMakeLists.txt.socket
- socket/io_modules/alert/email.lua
- socket/modules/heka/alert/email.lua
This is an optional field in the config that if set to a string appends said string to the footer of alert emails.
> Add support for appending an alert email footer

- socket/CMakeLists.txt.socket
- socket/sandboxes/heka/output/heka_tcp.lua
This feature allows data to be sent to an unreliable endpoint without
backpressuring the system. The delivery is simply best effort.
> Allow heka_tcp output to drop messages on connection/send failures

- syslog/CMakeLists.txt
- syslog/io_modules/decoders/syslog.lua
- syslog/tests/integration/tutorial/run/analysis/verify_grammar_module_keep.cfg
- syslog/tests/integration/tutorial/run/analysis/verify_grammar_module_keep.lua
- syslog/tests/integration/tutorial/run/input/grammar_module_keep.cfg
Hello Trink,
This patch is written to solve my problem, which was that the original Payload dropped off of my messages when using a sub_decoder in the syslog module.
I'm just hacking away, so do tell me if I need to proceed in a different way. I kept an eye on how the nginx module supports this option, and added a small integration test.
> Implement payload_keep option for subdecoders

- socket/CMakeLists.txt.socket
- socket/sandboxes/heka/output/heka_tcp.lua
this is to avoid socket.connect blocking the creation of the sandbox.
We had a case were the heka_tcp server was listening but the socket.connect would not complete (and it does not seem to timedout neither), so hindsight seems to be blocked creating this output sandbox and the hindsight.cp checkpoint file was not created.
> Create client in process_message

- taskcluster/sql/task_duration_estimates.sql
task_duration_estimates creates the file that mach try fuzzy can ask, for mean task durations.
> Add new scheduled query for mach try fuzzy

- taskcluster/cloud_functions/mach_try_table_exports/mach_try_table_exports.py
- taskcluster/cloud_functions/mach_try_table_exports/requirements.txt
- taskcluster/sql/derived_kind_costs.sql
- taskcluster/sql/derived_taskgroup_costs.sql
- taskcluster/sql/machtry_quantiles.sql
Updated some of the derivation queries with the needed values. I'll go through and have a clear-up soon, to avoid duplication.
I've added some automation to export the tables required for `mach try fuzzy --show-estimates` using cloud scheduler and a cloud function. Storing those here.
> Updated queries and gcp automation

- taskcluster/io_modules/decoders/taskcluster/live_backing_log.lua
- taskcluster/tests/integration/taskcluster/run/analysis/verify_error.lua
After the new cluster deployment the old URL should fail to fetch
current task data from queue.taskcluster.net and the new migration URL
will become active after the first successful retrieval.
> Issue 475 - Add a migration URL for automatic switch over

- syslog/CMakeLists.txt
- syslog/modules/lpeg/sendmail.lua
- syslog/tests/sendmail.lua
I ran into a mail server reply with "Hostname=...." stuff which overwrote the Hostname key set by the parent (syslog) decoder.
> Untrust the stat= key; value can contain garbage

- lfs/CMakeLists.txt.lfs
- lfs/sandboxes/heka/input/tail.lua
```
1574110765512931326 [info] input.tail starting
1574110765513067259 [debug] input.tail invalid checkpoint: 48641602 end: 79, starting from the beginning
1574110765513160998 [info] analysis_plugins starting thread: 0
```
> Issue #485 - Add a test for a checkpoint beyond the EOF

- cmake/sandbox_ep_test.cmake
- cmake/sandbox_module.cmake
if the {CMAKE_CURRENT_SOURCE_DIR}/tests directory does not exist, cmake
raise an error on Debian Buster.
> Fix cmake copy_directory issue on Debian Buster

- taskcluster/sql/derived_taskgroup_costs.sql
The previous version of this query would leave rows with partial data in if a
task group spanned more than one day. For example, if taskGroupId A had entries
on the 1st, 2nd and 3rd of the month, then when calculated on the 1st it would
sum all tasks and costs. When the 1st was >5 days ago, it would add a new row
counting all tasks that happened on the 2nd onwards, meaning that the
mean/median values for costs per task group would drop significantly.
This version uses a merge instead of a flat delete to update existing rows if
present. Duplicates have already been removed.
> Update derived_taskgroup_costs scheduled query

- taskcluster/sql/derived_kind_costs.sql
- taskcluster/sql/derived_test_suite_costs.sql
- taskcluster/sql/derived_workertype_costs.sql
- taskcluster/sql/derived_workertype_costs_community.sql
- taskcluster/sql/derived_workertype_costs_stage.sql
When rolling up the costs based on the org chart, a lot of costs are orphaned:
1. Collaborators
2. Github CI activity where a person's Github username isn't on people.m.o
3. Other activity from people in the org chart but who are using other identities for commits
Since the bulk of these is likely collaborators, this change adds a default in the situation where the `join` with `person_mozilla_com` produces no management chain. Adding the CEO allows the total in the reports to line up with the data that doesn't sort things this way, and reinforces the idea that they're ultimately accountable for the cost. The fake manager "Collaborator" acts as an intermediary to avoid polluting the CEO's direct reports and lets us view these other identities as a group.
(I've not yet deployed these …
> [taskclusteretl] Add default management chain for unknown identities

- elasticsearch/sandboxes/heka/output/elasticsearch_bulk_api.lua
I have pulled in the original #201, but I don't think I can push to that branch. I have based my work a bit on it.
I wonder if the module cannot go back to use the plain 'http.request': has support for passing it a connection factory: http://w3.impa.br/~diego/software/luasocket/http.html . Let me know what you think, as it is slightly more work.
I haven't built a test! Perhaps you have a suggestion on if, and how to test this?
> Elastic tls

- taskcluster/sandboxes/heka/input/taskcluster_capacity.lua
For https://bugzilla.mozilla.org/show_bug.cgi?id=1681843. It is my understanding that the static provider pool configuration are statically created outside of taskcluster control and these can be ignored as part of the import. We do manage these static deployments of resources in the ETL directly. 
Tested the change on taskclusteretl-dev environment. 
r?
> taskclusteretl: exclude static providers in worker pool configuration

- .circleci/config.yml
- docker_push.sh
TravisCI org is no longer working reliably so I've switched to using CircleCI. Tested build, test and deploy flow using the `test` branch [1]. I have *not* ported over the artifact publishing step defined in the travis-ci configuration, which I believe publishes RPMs to S3 [2]. I don't believe we need this anymore but let me know if we still want to maintain this.
[1] https://app.circleci.com/pipelines/github/mozilla-services/lua_sandbox_extensions/11/workflows/87abaf65-2b28-48c9-9572-e7ec745e1066
[2]  https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/.travis.yml#L18-L23
> Add circleci configuration
