mozilla-services/lua_sandbox_extensions

- rjson/index.md
- rjson/rjson.cpp
It might be useful to pull out a subset of the JSON as a string similar to what we do here: https://github.com/mozilla-services/data-pipeline/blob/master/heka/sandbox/decoders/extract_telemetry_dimensions.lua#L212-L218.
> rjson value as string

- moz_telemetry/CMakeLists.txt
- moz_telemetry/sandboxes/heka/input/moz_telemetry_s3_landfill.lua
> Add the uncompress/transformed JSON back to the submission field

- elasticsearch/CMakeLists.txt
- elasticsearch/modules/heka/elasticsearch.lua
- elasticsearch/modules/heka/elasticsearch/payload.lua
- elasticsearch/sandboxes/heka/output/elasticsearch_bulk_api.lua
- heka/sandboxes/heka/output/heka_debug.lua
- kafka/CMakeLists.txt
- kafka/sandboxes/heka/input/heka_kafka.lua
- moz_telemetry/CMakeLists.txt
- moz_telemetry/modules/heka/elasticsearch/moz_telemetry.lua
- moz_telemetry/modules/moz_telemetry/extract_dimensions.lua
- moz_telemetry/modules/moz_telemetry/extract_tls_info.lua
- moz_telemetry/modules/moz_telemetry/webrtc.lua
- moz_telemetry/sandboxes/heka/analysis/moz_telemetry_payload_size.lua
- moz_telemetry/sandboxes/heka/input/moz_telemetry_s3_landfill.lua
- moz_telemetry/sandboxes/heka/output/moz_telemetry_http.lua
- moz_telemetry/sandboxes/heka/output/moz_telemetry_s3.lua
> new infra updates

- moz_telemetry/sandboxes/heka/input/moz_telemetry_s3_landfill.lua
- moz_telemetry/sandboxes/heka/output/moz_telemetry_http.lua
- no extract dimensions module on pass thru
- just use the address for the Host header
> Cleanup for moz sandbox testing

- moz_telemetry/sandboxes/heka/output/moz_telemetry_s3.lua
- use an external uploader that scans for the ".done" files
- remove zstd compression for the moment since we don't use it
- switch to streaming gzip compression to smooth out the load
> Remove the aws cli upload (sequential upload was too slow)

- lfs/CMakeLists.txt.lfs
> lfs extension also works with libc6 v2.13

- moz_telemetry/CMakeLists.txt
- moz_telemetry/io_modules/decoders/moz_telemetry/ping.lua
Same as #39, against a different branch.
> Vacuous schema

- parquet/CMakeLists.txt
- parquet/io_modules/lpeg/parquet.lua
- parquet/parquet.cpp
- parquet/sandboxes/heka/output/s3_parquet.lua
- parquet/tests/test.lua
- improve the error handling/cleanup for dissection bugs
- generalize the s3_parquet output to handle metadata and multiple
JSON objects
> Fix the rollback of record 0

- parquet/CMakeLists.txt
- parquet/index.md
- parquet/io_modules/lpeg/parquet.lua
- parquet/parquet.cpp
- parquet/sandboxes/heka/output/s3_parquet.lua
- parquet/tests/test.lua
- Fix nested repetition level computation bug
- Overwrite the output when testing from the Hindsight Admin UI
> Bugzilla 1325679 Add MAP/LIST support to the HS parquet module

- socket/CMakeLists.txt.socket
- socket/sandboxes/heka/output/heka_tcp.lua
> Issue 65 heka_tcp output infinite loop

- elasticsearch/sandboxes/heka/output/elasticsearch_bulk_api.lua
You can now choose to discard_on_error or abort_on_error,
after retrying max_retry.
If both discard_on_error and abort_on_error are false, retry forever
reopenning against dev branch
> elasticsearch_bulk_api: rework error handling

- moz_telemetry/CMakeLists.txt
- moz_telemetry/io_modules/decoders/moz_telemetry/ping.lua
> Bugzilla 1337927 - Add support for loading versioned schemas

- moz_telemetry/CMakeLists.txt
- moz_telemetry/io_modules/decoders/moz_telemetry/ping.lua
> Include the schema filename with the parse error

- moz_telemetry/io_modules/decoders/moz_telemetry/ping.lua
- moz_telemetry/sandboxes/heka/analysis/moz_telemetry_doctype_monitor.lua
- moz_telemetry/tests/hindsight/run/analysis/doctype_monitor.cfg
- moz_telemetry/tests/hindsight/run/input/doctype_monitor.lua
- moz_telemetry/tests/hindsight/run/output/doctype_monitor.lua
> Bugzilla 1342111 - Filter duplicate documentIds out of the primary data set

- moz_telemetry/CMakeLists.txt
- moz_telemetry/io_modules/moz_telemetry/s3.lua
- moz_telemetry/sandboxes/heka/output/moz_telemetry_s3.lua
- moz_telemetry/tests/hindsight/moz_telemetry_s3.json
- moz_telemetry/tests/hindsight/moz_telemetry_s3_experiments.json
- moz_telemetry/tests/hindsight/run/input/doctype_monitor.lua
- moz_telemetry/tests/hindsight/run/input/moz_telemetry_s3.cfg
- moz_telemetry/tests/hindsight/run/input/moz_telemetry_s3.lua
- moz_telemetry/tests/hindsight/run/output/moz_telemetry_s3.cfg
> Bugzilla 1353110 - Add experiment support to the telemetry s3 output

- moz_telemetry/sandboxes/heka/output/moz_telemetry_s3.lua
- moz_telemetry/tests/hindsight/run/input/moz_telemetry_s3.lua
- moz_telemetry/tests/hindsight/run/output/moz_telemetry_s3.cfg
> Add a configuration option to write the experiments to a different dir

- parquet/parquet.cpp
- parquet/tests/test.lua
> Bugzilla 1387256 Preserve the list order in the parquet output

- geoip/CMakeLists.txt
- geoip/CMakeLists.txt.geoip
> Fix for #164 update lua-geoip to 0.2.0

- moz_telemetry/tests/hindsight/run/input/moz_telemetry_s3.lua
- moz_telemetry/tests/hindsight/run/output/moz_telemetry_s3.cfg
Mirrors changes to the prod config and adds tests for those changes
> Update tests to reflect updated experiment config

- CMakeLists.txt
- README.md
- jose/CMakeLists.txt
- openssl/CMakeLists.txt.openssl
- ssl/CMakeLists.txt.ssl
to be compatible with debian stretch and fix #202
> update libssl dependencies to allow libssl1.0.2

- lpeg/CMakeLists.txt.lpeg
- lpeg/modules/lpeg/escape_sequences.lua
- lpeg/modules/lpeg/logfmt.lua
- lpeg/tests/escape_sequences.lua
- lpeg/tests/logfmt.lua
- lpeg/tests/test.lua
> Add a logfmt log parser

- README.md
- lpeg/io_modules/lpeg/sub_decoder_util.lua
- lpeg/modules/lpeg/printf.lua
- moz_logging/CMakeLists.txt
- moz_logging/io_modules/decoders/moz_logging/line_splitter.lua
- syslog/io_modules/decoders/syslog.lua
Add an optional mutable argument to decode so sub_decoders know
when it is safe to apply changes directly to the existing message.
> Refactor the sub_decoder setup so it can be used in other plugins

- heka/CMakeLists.txt
- heka/sandboxes/heka/input/file.lua
- lfs/CMakeLists.txt.lfs
- lfs/sandboxes/heka/input/tail.lua
- lpeg/modules/lpeg/mysql.lua
- lpeg/tests/mysql.lua
- refactor tail.lua multi-line support
- fix the sql slow query host capture discovered during testing
> Issue 244 - Add multi-line log support to the file input plugin

- moz_ingest/io_modules/decoders/moz_ingest/common.lua
Follow up from [this discussion](https://github.com/mozilla-services/lua_sandbox_extensions/pull/257#discussion_r171860136) so we don't have to revisit this issue in the future.
Here are some examples of "bogus" first addresses that can't be looked up:
| name: X-Forwarded-For type: 0 representation: <nil> value: 02734648, 27.110.42.43
| name: X-Forwarded-For type: 0 representation: <nil> value: 10.1.37.93, 210.162.19.91
| name: X-Forwarded-For type: 0 representation: <nil> value: 10.1.64.40, 103.84.167.146
| name: X-Forwarded-For type: 0 representation: <nil> value: 10.16.10.116, 59.190.151.159
| name: X-Forwarded-For type: 0 representation: <nil> value: 10.40.18.195, 103.84.167.146
| name: X-Forwarded-For type: 0 representation: <nil> value: 10.6.1.31, 103.84.167.146
| name: …
> Add some context for using last v. first XFF IP

- moz_ingest/CMakeLists.txt
- moz_ingest/io_modules/decoders/moz_ingest/common.lua
- moz_ingest/tests/cities1000-test.txt
- moz_ingest/tests/integration/decoder_common/run/analysis/verify_decoder.lua
- moz_ingest/tests/integration/decoder_common/run/input/test_decoder.cfg
- moz_telemetry/tests/integration/decoder_telemetry/run/analysis/verify_decoder.lua
- moz_telemetry/tests/integration/decoder_telemetry/run/input/test_decoder.cfg
this may be easier to use, and easier for data review than adding geoname.
> Bug 1447652 - Add subdivisions to moz_ingest geoip lookup

- moz_ingest/io_modules/decoders/moz_ingest/common.lua
> fix bug in moz_ingest

- .travis.yml
- Dockerfile
- artifact_push.sh
Discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1445727#c4
> Travis artifacts

- Dockerfile
- streaming_algorithms now depends on the heka module
> Fix up the package installation order for the updated dependency

- moz_logging/CMakeLists.txt
- moz_logging/io_modules/decoders/moz_logging/json_heka.lua
ensure dh is non nil before it is used in json_heka
> handle nil dh in json_heka decoder

- moz_security/CMakeLists.txt
- moz_security/index.md
- moz_security/modules/heka/iprepd.lua
- moz_security/sandboxes/heka/analysis/moz_security_hh.lua
- moz_security/sandboxes/heka/analysis/moz_security_iprepd_alerts.lua
- moz_security/sandboxes/heka/output/moz_security_iprepd.lua
- moz_security/tests/hindsight/hindsight.cfg
- moz_security/tests/hindsight/iprepd_submit/run/input/generate_data.cfg
- moz_security/tests/hindsight/iprepd_submit/run/input/generate_data.lua
- moz_security/tests/hindsight/iprepd_submit/run/output/iprepd.cfg
- moz_security/tests/hindsight/run.sh
- moz_security/tests/integration/analysis_hh/run/analysis/hh_hawk.cfg
- moz_security/tests/integration/analysis_hh/run/output/hh_hawk_verification.lua
- moz_security/tests/integration/analysis_iprepd_alerts/run/analysis/iprepd_alerts.cfg
- moz_security/tests/integration/analysis_iprepd_alerts/run/input/generate_data.cfg
- moz_security/tests/integration/analysis_iprepd_alerts/run/input/generate_data.lua
- moz_security/tests/integration/analysis_iprepd_alerts/run/output/verification.cfg
- moz_security/tests/integration/analysis_iprepd_alerts/run/output/verification.lua
Mostly just a bunch of renaming here, but in addition:
- Split violations up in batches when submitting them to the API
- Add an integration test for alerting
- Add a manual test for iprepd violation submission from hindsight
- When a violation is applied that has an exception on it, don't consider it for an alert
> Convert tigerblood submission to iprepd

- moz_security/CMakeLists.txt
- moz_security/sandboxes/heka/analysis/moz_security_http_error_rate.lua
- moz_security/tests/integration/analysis_error_rate/run/analysis/err.cfg
- moz_security/tests/integration/analysis_error_rate/run/analysis/err_hawk.cfg
- moz_security/tests/integration/analysis_error_rate/run/input/generate_err.cfg
- moz_security/tests/integration/analysis_error_rate/run/input/generate_err.lua
- moz_security/tests/integration/analysis_error_rate/run/input/generate_err_hawk.cfg
- moz_security/tests/integration/analysis_error_rate/run/output/err_hawk_verification.cfg
- moz_security/tests/integration/analysis_error_rate/run/output/err_hawk_verification.lua
- moz_security/tests/integration/analysis_error_rate/run/output/err_verification.cfg
- moz_security/tests/integration/analysis_error_rate/run/output/err_verification.lua
Adds analysis sandbox that will generate iprepd violation notices on
high HTTP client error rates.
> http_error_rate: generate violation messages on high client error rate

- gcp/CMakeLists.txt
- gcp/common.cpp
- gcp/common.h
- gcp/pubsub.cpp
- gcp/pubsub.md
- gcp/sandboxes/heka/input/gcp_pubsub.lua
- gcp/sandboxes/heka/output/gcp_pubsub.lua
- gcp/tests/hindsight/run/input/load.cfg
- gcp/tests/hindsight/run/input/load1.cfg
- gcp/tests/hindsight/run/input/load2.cfg
- gcp/tests/hindsight/run/input/load3.cfg
- gcp/tests/hindsight/run/input/sub.cfg
- gcp/tests/hindsight/run/input/testdata.lua
- gcp/tests/hindsight/run/output/pub.cfg
- gcp/tests/hindsight/run/output/pub1.cfg
- Move batching from the plugin into the library
> Add attribute support for GCP pub/sub

- moz_ingest/CMakeLists.txt
- moz_ingest/sandboxes/heka/analysis/moz_ingest_doctype_monitor.lua
Track the previous top N errors and suppress the alert if the current
error is one of those
> Issue 431 - Reduce the ingestion error monitor noise

- CMakeLists.txt
- Dockerfile
- amqp/CMakeLists.txt
- amqp/amqp.c
- amqp/amqp.def
- amqp/index.md
- amqp/sandboxes/heka/input/amqp.lua
- Consumer only, needed to read the CI jobs exchange
> Add an AMQP module

- taskcluster/CMakeLists.txt
- taskcluster/bin/realorg.lua
- taskcluster/sandboxes/heka/analysis/taskcluster_influx_workertype.lua
- taskcluster/sandboxes/heka/analysis/taskcluster_plugin_monitor.lua
- taskcluster/sandboxes/heka/output/influx_output.lua
- taskcluster/schemas/taskcluster/mozilla_com.1.bq.json
- taskcluster/sql/derived_test_suite_costs.sql
- Mozilla organization data
- utility functions
- schema/query updates
> Influxdb - near real time metric output

- amqp/CMakeLists.txt
- amqp/amqp.c
- amqp/index.md
- amqp/sandboxes/heka/input/amqp.lua
- Improve configuration error handling
> Add support for a vhost configuration

- ssl/CMakeLists.txt
- ssl/CMakeLists.txt.ssl
> Update luasec to v0.9 to allow libssl1.1 dependency

- taskcluster/CMakeLists.txt
- taskcluster/sql/derived_daily_cost_per_workertype.sql
- taskcluster/sql/derived_kind_costs.sql
- taskcluster/sql/derived_test_suite_costs.sql
- taskcluster/sql/derived_workertype_costs.sql
- add a cluster column to the cost table
- update AWS cost extraction account ids
> Add GCP cost information

- elasticsearch/CMakeLists.txt
- elasticsearch/sandboxes/heka/output/elasticsearch_bulk_api.lua
And, when #518 is through the gate, I'd like some basic auth sauce added.
> add basic auth
